import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import fs from 'node:fs';
import path from 'node:path';

const site = process.env.PUBLIC_SITE_URL ?? 'https://startup-perks.com';

const REDIRECT_MAP_FILE = 'functions/go/_map.ts';

function buildRedirectMap(rootDir) {
  const perksDir = path.join(rootDir, 'src/content/perks');
  const redirects = {};
  if (!fs.existsSync(perksDir)) return redirects;
  for (const file of fs.readdirSync(perksDir)) {
    if (!file.endsWith('.md')) continue;
    const raw = fs.readFileSync(path.join(perksDir, file), 'utf8');
    const frontmatter = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!frontmatter) continue;
    if (/^isActive:\s*false\s*$/m.test(frontmatter[1])) continue;
    const applyUrl = frontmatter[1].match(/^applyUrl:\s*['"]?(\S+?)['"]?\s*$/m);
    if (!applyUrl) continue;
    redirects[file.replace(/\.md$/, '')] = applyUrl[1];
  }
  return redirects;
}

function writeRedirectMap(rootDir) {
  const redirects = buildRedirectMap(rootDir);
  const entries = Object.keys(redirects)
    .sort()
    .map((slug) => `  ${JSON.stringify(slug)}: ${JSON.stringify(redirects[slug])},`)
    .join('\n');
  const contents = `// AUTO-GENERATED by the redirect-map Astro integration. Do not edit.\nexport const REDIRECTS: Record<string, string> = {\n${entries}\n};\n`;
  const mapPath = path.join(rootDir, REDIRECT_MAP_FILE);
  fs.mkdirSync(path.dirname(mapPath), { recursive: true });
  fs.writeFileSync(mapPath, contents);
}

function redirectMap() {
  return {
    name: 'redirect-map',
    hooks: {
      'astro:config:setup': () => {
        writeRedirectMap(process.cwd());
      },
    },
  };
}

// https://astro.build/config
export default defineConfig({
  site,
  integrations: [sitemap(), redirectMap()],
});
