import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import fs from 'node:fs';
import path from 'node:path';

const site = process.env.PUBLIC_SITE_URL ?? 'https://startup-perks.com';

const REDIRECT_MAP_FILE = 'functions/go/_map.ts';

function buildRedirectMap(rootDir) {
  const perksDir = path.join(rootDir, 'src/content/perks');
  const redirects = {};
  if (!fs.existsSync(perksDir)) return redirects;
  for (const file of fs.readdirSync(perksDir)) {
    if (!file.endsWith('.md')) continue;
    const raw = fs.readFileSync(path.join(perksDir, file), 'utf8');
    const frontmatter = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!frontmatter) continue;
    if (/^isActive:\s*false\s*$/m.test(frontmatter[1])) continue;
    const applyUrl = frontmatter[1].match(/^applyUrl:\s*['"]?(\S+?)['"]?\s*$/m);
    if (!applyUrl) continue;
    redirects[file.replace(/\.md$/, '')] = applyUrl[1];
  }
  return redirects;
}

function writeRedirectMap(rootDir) {
  const redirects = process.env.DISABLE_REDIRECTS === '1' ? {} : buildRedirectMap(rootDir);
  const entries = Object.keys(redirects)
    .sort()
    .map((slug) => `  ${JSON.stringify(slug)}: ${JSON.stringify(redirects[slug])},`)
    .join('\n');
  const contents = `// AUTO-GENERATED by the redirect-map Astro integration. Do not edit.\nexport const REDIRECTS: Record<string, string> = {\n${entries}\n};\n`;
  const mapPath = path.join(rootDir, REDIRECT_MAP_FILE);
  fs.mkdirSync(path.dirname(mapPath), { recursive: true });
  fs.writeFileSync(mapPath, contents);
  return redirects;
}

function makeDevGoMiddleware(redirects) {
  return (req, res, next) => {
    const url = req.url ?? '';
    const method = req.method ?? 'GET';
    if (!url.startsWith('/go/') || (method !== 'GET' && method !== 'HEAD')) return next();
    const slug = decodeURIComponent(url.replace(/^\/go\//, '').replace(/[/?].*$/, ''));
    const target = redirects[slug];
    if (!target || !/^https?:\/\//.test(target)) {
      res.statusCode = 302;
      res.setHeader('Location', '/');
      res.end();
      return;
    }
    res.statusCode = 302;
    res.setHeader('Location', target);
    res.end();
  };
}

function redirectMap() {
  let redirects = {};
  return {
    name: 'redirect-map',
    hooks: {
      'astro:config:setup': () => {
        redirects = writeRedirectMap(process.cwd());
      },
      'astro:server:setup': ({ server }) => {
        server.middlewares.stack.unshift({ route: '', handle: makeDevGoMiddleware(redirects) });
      },
    },
  };
}

// https://astro.build/config
export default defineConfig({
  site,
  integrations: [sitemap(), redirectMap()],
});
